language: python
python:
- "3.4"
install: "pip install -r requirements.txt"
script: 
- SECRET_KEY="anything"./manage.py test

[![Build Status](https://travis-ci.org/conorc470/django-ecommerce-project.svg?branch=master)](https://travis-ci.org/conorc470/django-ecommerce-project)